# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [105]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from pathlib import Path

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [4]:
# Upload credit_card_transactions.csv to Colab
from google.colab import files

csv_file = files.upload()

Saving applicants_data.csv to applicants_data.csv

In [43]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv('applicants_data.csv')

# Review the DataFrame
applicant_data_df.head(10)

        EIN  ... IS_SUCCESSFUL
0  10520599  ...             1
1  10531628  ...             1
2  10547893  ...             0
3  10553066  ...             1
4  10556103  ...             1
5  10556855  ...             1
6  10558440  ...             1
7  10566033  ...             1
8  10570430  ...             1
9  10571689  ...             0

[10 rows x 12 columns]

In [29]:
# Review the data types associated with the columns
applicant_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

In [42]:
num_var_df = applicant_data_df['INCOME_AMT','ASK_AMT']

KeyError: ignored

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [31]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(['EIN','NAME'], axis=1)

# Review the DataFrame
applicant_data_df.head()

KeyError: ignored

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [47]:
# Create a list of categorical variables 
categorical_variables = ["APPLICATION_TYPE","AFFILIATION","CLASSIFICATION","USE_CASE","STATUS","SPECIAL_CONSIDERATIONS"
                        ]

# Display the categorical variables list
print(categorical_variables)

['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'STATUS', 'SPECIAL_CONSIDERATIONS']

In [48]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [49]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [50]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)


# Review the DataFrame
encoded_df.head()

   APPLICATION_TYPE_T10  ...  SPECIAL_CONSIDERATIONS_Y
0                   1.0  ...                       0.0
1                   0.0  ...                       0.0
2                   0.0  ...                       0.0
3                   0.0  ...                       0.0
4                   0.0  ...                       0.0

[5 rows x 103 columns]

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [66]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([encoded_df, applicant_data_df['ASK_AMT']], axis=1)

In [67]:
encoded_df = pd.concat([encoded_df, applicant_data_df['IS_SUCCESSFUL']], axis=1)

In [69]:

encoded_df = encoded_df.drop(['INCOME_AMT'], axis=1)

In [70]:
# Review the Dataframe
encoded_df.head()

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...  ASK_AMT  IS_SUCCESSFUL
0                   1.0                   0.0  ...     5000              1
1                   0.0                   0.0  ...   108590              1
2                   0.0                   0.0  ...     5000              0
3                   0.0                   0.0  ...     6692              1
4                   0.0                   0.0  ...   142590              1

[5 rows x 108 columns]

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [71]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y.sample()

       IS_SUCCESSFUL  IS_SUCCESSFUL
30469              1              1

In [72]:

# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.loc[:, encoded_df.columns != 'IS_SUCCESSFUL']

# Review the features DataFrame
X.head()

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...  ASK_AMT  ASK_AMT
0                   1.0                   0.0  ...     5000     5000
1                   0.0                   0.0  ...   108590   108590
2                   0.0                   0.0  ...     5000     5000
3                   0.0                   0.0  ...     6692     6692
4                   0.0                   0.0  ...   142590   142590

[5 rows x 106 columns]

### Step 6: Split the features and target sets into training and testing datasets.

In [73]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [74]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = StandardScaler()

X_scaler.fit(X_train)
# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [91]:
# Define the the number of inputs (features) to the model
number_input_features = 106

# Review the number of features
number_input_features

106

In [92]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [93]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  15
# Review the number hidden nodes in the first layer
hidden_nodes_layer1

15

In [94]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  7

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

7

In [95]:
# Create the Sequential model instance
nn = Sequential()

In [96]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [97]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [98]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="linear"))

In [99]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 15)                1605

 dense_4 (Dense)             (None, 7)                 112

 dense_5 (Dense)             (None, 1)                 8

=================================================================
Total params: 1,725
Trainable params: 1,725
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [100]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [101]:
# Fit the model using 50 epochs and the training data
deep_net_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7767 - accuracy: 0.6827
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6843 - accuracy: 0.7173
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6730 - accuracy: 0.7208
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6708 - accuracy: 0.7221
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6738 - accuracy: 0.7224
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6647 - accuracy: 0.7238
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6528 - accuracy: 0.7242
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6460 - accuracy: 0.7232
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6396 - accuracy: 0.7237
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6374 - accuracy: 0.7243
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6325 - accuracy: 0.7253
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6325 - accuracy: 0.7249
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6333 - accuracy: 0.7250
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6338 - accuracy: 0.7253
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6348 - accuracy: 0.7237
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6395 - accuracy: 0.7250
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6329 - accuracy: 0.7252
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6375 - accuracy: 0.7252
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6462 - accuracy: 0.7248
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6359 - accuracy: 0.7255
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6431 - accuracy: 0.7196
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6355 - accuracy: 0.7262
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6325 - accuracy: 0.7249
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6308 - accuracy: 0.7267
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6505 - accuracy: 0.7245
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6496 - accuracy: 0.7256
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6466 - accuracy: 0.7260
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6474 - accuracy: 0.7254
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6373 - accuracy: 0.7259
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6237 - accuracy: 0.7261
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6240 - accuracy: 0.7264
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6263 - accuracy: 0.7263
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6256 - accuracy: 0.7254
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6202 - accuracy: 0.7247
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6166 - accuracy: 0.7262
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6221 - accuracy: 0.7260
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6208 - accuracy: 0.7268
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6303 - accuracy: 0.7251
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6327 - accuracy: 0.7128
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6210 - accuracy: 0.7221
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6200 - accuracy: 0.7270
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6211 - accuracy: 0.7272
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6192 - accuracy: 0.7270
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6227 - accuracy: 0.7269
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6163 - accuracy: 0.7270
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6300 - accuracy: 0.7113
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6180 - accuracy: 0.7257
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6153 - accuracy: 0.7263
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6105 - accuracy: 0.7267
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6114 - accuracy: 0.7262

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [102]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)


# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6027 - accuracy: 0.7257 - 370ms/epoch - 1ms/step
Loss: 0.6026527881622314, Accuracy: 0.7257142663002014

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [106]:
# Set the model's file path
file_path = Path("AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [107]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

106

In [108]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [109]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 30

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

30

In [111]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [115]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))


# Output layer
nn_A1.add(Dense(units=1, activation="linear"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 30)                3210

 dense_10 (Dense)            (None, 1)                 31

 dense_11 (Dense)            (None, 30)                60

 dense_12 (Dense)            (None, 1)                 31

=================================================================
Total params: 3,332
Trainable params: 3,332
Non-trainable params: 0
_________________________________________________________________

In [116]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [117]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8384 - accuracy: 0.6515
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.6991
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6516 - accuracy: 0.7090
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6283 - accuracy: 0.7198
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6207 - accuracy: 0.7231
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6247 - accuracy: 0.7233
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6304 - accuracy: 0.7208
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6242 - accuracy: 0.7205
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6247 - accuracy: 0.7225
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6353 - accuracy: 0.7086
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6160 - accuracy: 0.7230
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6350 - accuracy: 0.6965
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6102 - accuracy: 0.7233
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6277 - accuracy: 0.7098
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6160 - accuracy: 0.7195
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6115 - accuracy: 0.7247
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6096 - accuracy: 0.7244
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6114 - accuracy: 0.7253
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6088 - accuracy: 0.7223
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6095 - accuracy: 0.7263
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6131 - accuracy: 0.7224
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6145 - accuracy: 0.7231
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6134 - accuracy: 0.7255
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6122 - accuracy: 0.7268
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6129 - accuracy: 0.7255
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7108 - accuracy: 0.6761
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6310 - accuracy: 0.6903
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5962 - accuracy: 0.7234
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5965 - accuracy: 0.7234
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5990 - accuracy: 0.7239
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5957 - accuracy: 0.7241
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6111 - accuracy: 0.7009
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5972 - accuracy: 0.7241
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5939 - accuracy: 0.7265
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5973 - accuracy: 0.7230
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6007 - accuracy: 0.7257
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6008 - accuracy: 0.7219
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6015 - accuracy: 0.7169
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5948 - accuracy: 0.7247
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5962 - accuracy: 0.7197
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5915 - accuracy: 0.7238
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5884 - accuracy: 0.7256
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5917 - accuracy: 0.7258
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5941 - accuracy: 0.7255
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5947 - accuracy: 0.7245
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5931 - accuracy: 0.7251
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5947 - accuracy: 0.7217
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5911 - accuracy: 0.7262
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5937 - accuracy: 0.7242
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5890 - accuracy: 0.7264

#### Alternative Model 2

In [118]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

106

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [119]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 3

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

3

In [120]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [121]:
# First hidden layer
# YOUR CODE HERE
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu"))


# Output layer
nn_A2.add(Dense(units=1, activation="linear"))


# Check the structure of the model
nn_A2.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_13 (Dense)            (None, 3)                 321

 dense_14 (Dense)            (None, 1)                 4

=================================================================
Total params: 325
Trainable params: 325
Non-trainable params: 0
_________________________________________________________________

In [122]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [123]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 8.2288 - accuracy: 0.4665

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [124]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.6027 - accuracy: 0.7257 - 312ms/epoch - 1ms/step
Loss: 0.6026527881622314, Accuracy: 0.7257142663002014

In [125]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5981 - accuracy: 0.7213 - 390ms/epoch - 1ms/step
Loss: 0.5980887413024902, Accuracy: 0.7212827801704407

In [126]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 8.1631 - accuracy: 0.4708 - 328ms/epoch - 1ms/step
Loss: 8.163082122802734, Accuracy: 0.4707871675491333

### Step 3: Save each of your alternative models as an HDF5 file.

In [127]:
# Set the file path for the first alternative model
file_path_A1 = Path("AlphabetSoupA1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path_A1)

In [128]:
# Set the file path for the second alternative model
file_path_A2 = Path("AlphabetSoupA2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path_A2)